data:
  image: busybox:latest
  volumes:
    - /usr/share/elasticsearch/data


elasticsearch:
  image: elasticsearch:1.5.0
  volumes_from:
    - data


kibana:
  image: madron/kibana
  links:
    - elasticsearch:elasticsearch
  ports:
    - 80:5601
